### ISSUE TITLE
ValidationError: <property_name> does not match '^(([\\w-]*)?:([\\w ]+))$

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#10]
Extracted propnames in a resource's cardinalities array are not accepted by the [knora-schema.json validation](https://github.com/dasch-swiss/dsp-tools/blob/main/knora/dsplib/utils/knora-schema.json#L323-L339), because the validator expects the following form:

` :<propname>`
or 
`<other-onto>:<propname>`

**Comment by musicEnfanthen** [comment]
Compare #4

**Comment by irinaschubert** [comment]
see https://github.com/dasch-swiss/dsp-tools/issues/40

Hi @musicEnfanthen , is this issue still open for you? I see that https://github.com/dasch-swiss/salsah-migration-scripts/issues/4, which you referenced here, has been closed a while ago. If not, could you explain what you mean by "extracted propnames"? The validation seems correct to me but maybe I don't understand what you mean.

**Comment by musicEnfanthen** [comment]
@irinaschubert No, I guess it can be closed. Property names are validating correctly at the moment in the export script. Thank you for checking.

**Comment by irinaschubert** [comment]
OK, thanks for the reply @musicEnfanthen. You can open a new issue if problems come up again.
