### ISSUE TITLE
Label instead of name is used for property name

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#11]
In `fetchProperties` the fetched property's **label** is used for the mapped properties **name** what results in a conflict with the names of properties (listed as `propname`) in a resource.

Example:

property:
```
 {
                        "name": "weiterer Verlag",
                        "super": [
                            "hasValue"
                        ],
                        "object": "TextValue",
                        "labels": {
                            "de": "weiterer Verlag"
                        },
                        "comments": {
                            "de": "weiterer Verlag"
                        },
                        "gui_element": "Richtext",
                        "gui_attributes": {}
                    },
```

resource using this property:
```
{
                        "name": "Werk",
                        "super": "Resource",
                        "labels": {
                            "de": "Werk",
                            "fr": "\u0152uvre",
                            "it": "Opera",
                            "en": "Work"
                        },
                        "cardinalities": [
                            {
                                "propname": ":further_publisher_rt",
                                "cardinality": "0-n"
                            },
...
```

**Comment by ManuelRosenthaler** [comment]
I think i have just fixed this however i want to test it first befor pushing. (probably i only can test tomorrow and not today anymore)

**Comment by ManuelRosenthaler** [comment]
Fixed and pushed

**Comment by musicEnfanthen** [comment]
@ManuelRosenthaler  Something weird is happening after 0d66515 (double-checked that it was introduced by this commit) : 

Properties have now the correct name, but all other values of a property object are empty (super, object, gui_element, gui_attributes)

**Comment by ManuelRosenthaler** [comment]
Shit... i think i might know why that is... i will look into it as soon as possible. That said: Do you need it to be fixed fast? because i would only work at monday again... if its urgent then i can look into it during the weekend ^^

**Comment by ManuelRosenthaler** [comment]
@musicEnfanthen Ok i just looked into it. It seems that changing the name of the property from the "label" to its "name" triggers a cascade of dependencies that ere no longer fulfilled. 

Namely the line 357: 
    if labelId["label"] == tmpOnto["project"]["ontologies"][0]["properties"][-1]["name"]:
needed the "label". 

I'll need to go over all the code and see if there are any other cascade effects and how to fix them

**Comment by musicEnfanthen** [comment]
Thanks. No, no hurry. Monday is fine.

Yes, I think you are right. There are some cascade effects after the change to the name.

**Comment by musicEnfanthen** [comment]
In general, the logic of the whole section [L305-L366 ](https://github.com/dasch-swiss/salsah-migration-scripts/blob/main/SalsaToNew.py#L305-L366) has some redundancy in it, that makes it really hard to comprehend (repeated loops, variables that only serve the purpose to look up id's, etc.) and that could be simplified a lot. I guess that would also simplify the handling of the attributes.

If you want, I could provide a PR addressing this?

**Comment by ManuelRosenthaler** [comment]
Yes you are absolutely right. But I don't think a PR is necessary at the moment. I will not only solve this problem on mondays but also try to clean up the code a bit and take out redundancies.

Also, I couldn't resist to tackle the problem already and found a quickfix for the problem. But i think it's better i wait with the push until i made the code a bit more readable :)

**Comment by ManuelRosenthaler** [comment]
Now the code is refactured and this issue is properly fixed.
