### ISSUE TITLE
Project description is malformed

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#19]
Project descriptions are expected to have the following format (https://dasch-swiss.github.io/dsp-tools/dsp-tools-create/#descriptions):

`"descriptions": {"<lang>": "<string>", ...}`

At the moment, the project descriptions are extracted as follows:

`"descriptions": "<string>"`

Although this is syntactically correct and passes validation, it results in a 400 error when creating an ontology via knora-api:

```
Creating project failed: KNORA-ERROR: status code=400
Message:The request content was malformed:
Expected Collection as JsArray, but got "This is the special vocabulary for the Anton Webern Edition."
```

**Comment by musicEnfanthen** [comment]
Using the format

`"descriptions": {"en": "This is the special vocabulary for the Anton Webern Edition."},`

works fine.

**Comment by musicEnfanthen** [comment]
But indeed, the "malformed" form is what is coming from the API response.

Not sure about what can be done about this? @lrosenth any ideas?

**Comment by ManuelRosenthaler** [comment]
In the old Version the language information is not existing (like it is in the new one). Ad an "en" as the default language. (needs to be corrected by hand if necessary)
