### ISSUE TITLE
Resource names should use resTypeInfo name instead of label

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#20]
At the moment, resource names are extracted from the resourcetype label directly: https://github.com/dasch-swiss/salsah-migration-scripts/blob/main/SalsaToNew.py#L199

This can lead to an error when creating an ontology via knora-api, since the labels can include not allowed characters (like `-`, `:` etc.)

Instead, the resource names should be extracted from the name value in `resTypeInfo`, so only after the second API request in https://github.com/dasch-swiss/salsah-migration-scripts/blob/main/SalsaToNew.py#L209-L211

The name value will also include the vocabulary name in the form `<project>:<resource name>`, so it will have to be split up by colon.

Proposal:
```
for momResId in resourcetypes["resourcetypes"]:
    tmpOnto["project"]["ontologies"][0]["resources"].append({
        "name": "",    # empty value here
        "super": "",
        "labels": {},
        "comments": {},
        "cardinalities": []
     })

    # fetch restype_info
    req = requests.get('https://salsah.org/api/resourcetypes/{}?lang=all'.format(momResId["id"]))
    resType = req.json()
    resTypeInfo = resType["restype_info"]

    # fill in the name
    nameSplit = resTypeInfo["name"].split(":")
    tmpOnto["project"]["ontologies"][0]["resources"][-1]["name"] = nameSplit[1]

    # labels should also be taken from resTypeInfo
    # fill in the labels
    if resTypeInfo["label"] is not None and isinstance(resTypeInfo["label"], list):
        for label in resTypeInfo["label"]:
            tmpOnto["project"]["ontologies"][0]["resources"][-1]["labels"].update(
                {label["shortname"]: label["label"]})
```

**Comment by ManuelRosenthaler** [comment]
Integrated. Thx for the proposal!

**Comment by ManuelRosenthaler** [comment]
Perfect proposition. Integrated as is :)
