### ISSUE TITLE
ValidationError: 'LinkValue' is not one of allowed property objects

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#4]
Salsah's Resource Pointer are mapped to `LinkValue` object in https://github.com/dasch-swiss/salsah-migration-scripts/blob/main/SalsaToNew.py#L280

However, the object type `LinkValue` is not allowed in the `knora-schema.json`:  https://github.com/dasch-swiss/dsp-tools/blob/main/knora/dsplib/utils/knora-schema.json#L219-L242

Documentation says, [LinkValues](https://dasch-swiss.github.io/dsp-tools/dsp-tools-create/#linkvalue) have to be mapped to something like this:

`"object": ":<resource-name>"` or
` "object": "other-onto:<resource-name>"`

**Comment by musicEnfanthen** [comment]
After some investigation, it is possible to extract the LinkValue's resource names in the form needed for most project specific LinkValues. 

However, there remains a problem that `salsah:part_of` and `salsah:sequence_of` are Resource pointer with no specific LinkValue (can be any Resource). Same for those LinkValues pointing to `restypeid=0`.

**Comment by ManuelRosenthaler** [comment]
Found a Solution. I will push my solution tomorrow (and continue with the other issues)

**Comment by ManuelRosenthaler** [comment]
Fixed and pushed
