### ISSUE TITLE
langdetect detects wrong language

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#6]
In some cases, the non-deterministic detection behaviour of `langdetect` (see https://github.com/dasch-swiss/salsah-migration-scripts/blob/main/SalsaToNew.py#L233) leads to wrong language id's for comments. That's especially the case for very short comments, e.g.:

ID instead of country short code (or Indonesian)
```
{
      "propname": "date",
      "comments": {
            "id": "Datum"
       },
      "cardinality": "1"
},
```
```                           
{
        "propname": "date_death",
        "comments": {
              "id": "Sterbedatum"
        },
        "cardinality": "0-1"
},
```
Catalan (ca):
```
{
      "propname": "textincipit",
      "comments": {
              "ca": "Incipit eines Textes, Briefes, Liedtextes"
      },
      "cardinality": "0-1"
},
```

Norwegian:
```
{
       "propname": "address",
       "comments": {
                "no": "Adresse (Strassenname, Nummer etc.)"
       },
       "cardinality": "0-n"
},
```

Danish:
```
 {
        "propname": "transcription",
        "comments": {
                "da": "Transkription"
          },
          "cardinality": "0-n"
},
```

**Comment by musicEnfanthen** [comment]
Cf. https://stackoverflow.com/questions/37235932/python-langdetect-choose-between-one-language-or-the-other-only

**Comment by musicEnfanthen** [comment]
Fun fact: The word "Sterbedatum" gets detected as Indonesian (`id`) with a probability of 85%, as German with only 15%, and that only sometimes, mostly `de` not detected at all.

**Comment by musicEnfanthen** [comment]
Instead of using langdetect, we could just use the description shortname that keeps the language short code. Same approach is used for label language: https://github.com/dasch-swiss/salsah-migration-scripts/blob/main/SalsaToNew.py#L206-L207

**Comment by ManuelRosenthaler** [comment]
Ok, thats rather interesting xD I used langdetect since i found some errors on the original ontologies them selves. I thought i can correct them while running the import but it seems that the langdetect is trash... So i either search for another module that can detect languages that works better or import all the given languages - even tho some of them will be false
Edit: I will do the latter

**Comment by musicEnfanthen** [comment]
Yes, the latter seems appropriate. The wrong languages should be corrected in the data by the projects.

**Comment by ManuelRosenthaler** [comment]
@musicEnfanthen  Can you maybe still tell me in which ontologies and on which lines you found these examples from above? I want to check my solution on these :)
Edit: If it's too much work it's not that important... i can just get an overview with my own tests

**Comment by musicEnfanthen** [comment]
The examples above are from the Webern model when used with langdetect. The propnames are from the resource's cardinalities.

**Comment by ManuelRosenthaler** [comment]
Ok, it should be fixed now. I close this issue but the fix is pushed on the branch i opened. So it should be visible in git (if not pls tell me :) )

**Comment by musicEnfanthen** [comment]
Thanks, the approach works correctly.
