### ISSUE TITLE
ValidationError: <gui-attribute> is not of type integer

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#7]
According to the [knora-schema.json](https://github.com/dasch-swiss/dsp-tools/blob/main/knora/dsplib/utils/knora-schema.json#L277), gui-attributes like `size` have to be integer values. However, values are extracted as string values.

**Comment by ManuelRosenthaler** [comment]
Looks good! I will consult with Lukas this evening regarding a open question. If there is nothing new I will make the merge tonight :)

**Comment by ManuelRosenthaler** [comment]
Never mind. Lukas thought that the percentage works but in the newest version of the backend, percentages are not allowed... So if a percentage appears, then it will be replaced by a fixed number 250 (250 denotes the width of the input field)

**Comment by musicEnfanthen** [comment]
Thanks.
