### ISSUE TITLE
GUI value errors in projects

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/salsah-migration-scripts#9]
Collection of validation errors that are thrown for the different projects in SALSAH. These errors would to have be corrected by the projects in the SALSAH admin interface.

**Delille**
[ ] ValueError: Expected integer, but got 99% (delille noms_prenoms ['size', '99%'] <class 'str'>)
[ ] ValueError: Expected integer, but got 99% (delille auteur ['size', '99%'] <class 'str'>)

**Das Literarische Feuilleton**
[ ] ValueError: Expected integer, but got 100% (feuilleton pseudonym ['size', '100%'] <class 'str'>)
[ ] ValueError: Expected integer, but got 100% ((feuilleton autorname ['size', '100%'] <class 'str'>)

**Comment by ManuelRosenthaler** [comment]
hm... yes there should indeed be an integer. Maby i can change the percentage to be written as 99% -> 0.99? I'll check that with lukas

**Comment by musicEnfanthen** [comment]
Guess that 0.99 wouldn't work since it is float type not integer.

Not sure but is the `size` numprop really meant to hold percentage values?

**Comment by ManuelRosenthaler** [comment]
Oh crap, you are right... float does obviously not work... and no, i dont think that these should hold percentage values :) i'll need to ask lukas on how he wants them to be handled...

**Comment by ManuelRosenthaler** [comment]
I have been corresponding with Luke. In fact, it is correct that a percent is allowed to be in a string. Luke will change this in the validation. Thus the migration script does not need to be changed
